name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: sudo apt update && sudo apt install libusb-1.0-0-dev libsqlite3-dev ninja-build
    - name: make
      run: make

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: brew
      run: brew install sqlite pkg-config libusb ninja
    - name: make
      run: make

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel git make mingw-w64-i686-ninja mingw-w64-i686-libusb mingw-w64-i686-sqlite3 mingw-w64-i686-zlib mingw-w64-i686-gcc zip which ninja bash mingw-w64-x86_64-ninja
        path-type: inherit
    - uses: actions/checkout@v2
    - name: build
      shell: bash
      run: |
        echo $PATH
        export PATH=$PATH:/msys64/usr/bin
        find / -name ninja\*
        which ninja
        make

